spring.application.name=BackEnd-CodeSprint
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Servidor
server.servlet.context-path=/api/v1
server.port=8081

# JWT
jwt.secret=clave_secreta_para_jwt_debe_ser_muy_larga_32_caracteres
jwt.expiration=604800000

# Frontend
frontend.url=http://localhost:4200
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Amazon Rekognition
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-1
aws.rekognition.similarity-threshold=90.0

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# PayPal
PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
PAYPAL_SECRET=${PAYPAL_SECRET}
PAYPAL_BASE_URL=${PAYPAL_BASE_URL}

#IA
mcp.ai.base-url=http://localhost:8090
mcp.ai.timeout-seconds=30
recommendation.ai.base-url=http://localhost:8091

server.tomcat.max-http-form-post-size=10MB
spring.websocket.max-text-message-size=5242880


# JaaS (Jitsi as a Service) - 8x8

jaas.app-id=vpaas-magic-cookie-72f48789ab9b42efbbe17692eb27301e
jaas.key-id=vpaas-magic-cookie-72f48789ab9b42efbbe17692eb27301e/0b148c
jaas.private-key-path=classpath:jaas-private.pk

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG

