spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.security.oauth2.client.registration.google.client-id=dummy
spring.security.oauth2.client.registration.google.client-secret=dummy

cloudinary.cloud-name=dummy
cloudinary.api-key=dummy
cloudinary.api-secret=dummy

aws.access-key=dummy
aws.secret-key=dummy

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=torressusan.93@gmail.com
spring.mail.password=bkivhkitncsduyqf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true